buildscript {
    repositories {
        maven { url "/usr/share/maven-repo" }
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:2.2.2"
    }
}

allprojects {
    repositories {
        maven { url "/usr/share/maven-repo" }
        google()
        mavenCentral()
    }
}
